#!/usr/bin/env node
const fs=require('fs');const path=require('path');const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const exists=p=>fs.existsSync(path.join(root,p));const failures=[];
const html=read('site/index.html');const curriculum=read('site/curriculum/index.html');const organizations=read('site/organizations/index.html');const js=read('site/assets/js/main.js');
for(const text of ['AI skills for real life.','Human judgment at the center.','Edward Jones','Capital Property Care','Learn. Make. Check. Use.','Human judgment stays in control throughout.','A real need became a live business website.','Real deployment footage','Bring practical AI learning to your community.','Participant story and media shared with consent.'])if(!html.includes(text))failures.push(`Homepage missing visual-first copy: ${text}`);
for(const term of ['tool-neutral','community organizations','human judgment'])if(!html.toLowerCase().includes(term.toLowerCase()))failures.push(`Homepage missing positioning term: ${term}`);
for(const asset of ['site/assets/media/edward-story.mp4','site/assets/media/edward-deployment.mp4']){if(!exists(asset))failures.push(`Missing authentic participant media: ${asset}`);else if(fs.statSync(path.join(root,asset)).size<15000)failures.push(`Participant media unexpectedly small: ${asset}`);}
for(const ref of ['/assets/media/edward-story.mp4','/assets/media/edward-deployment.mp4','href="https://www.capitalpropertycare.com/"','/assets/css/visual-first.css?v=20260808-1','/assets/js/main.js?v=20260808-2'])if(!html.includes(ref))failures.push(`Homepage missing current visual/media reference: ${ref}`);
if(/drive\.google\.com|docs\.google\.com/i.test(html))failures.push('Homepage must not expose Google Drive or Google Docs links.');
if(/>(?:\s*)0[1-9](?:\s*)</.test(html))failures.push('Homepage contains numbered visual UI; approved direction is unnumbered.');
for(const pattern of [/Before we automate/i,/AI Capability Lab/i,/Day\s+\d+\s+of\s+\d+/i,/context engineering/i,/SozoRock Meridian|Meridian/i,/unlock your potential|transform your future|revolutionize|game[- ]changer|supercharge/i])if(pattern.test(html)||pattern.test(curriculum)||pattern.test(organizations))failures.push(`Public program pages contain removed product/hype pattern: ${pattern}`);
for(const [name,source] of [['homepage',html],['curriculum',curriculum],['organizations',organizations]])if(/href="mailto:/i.test(source))failures.push(`${name}: email-based link remains on a primary program page`);
const requiredOrganizationCopy=['Bring practical AI learning to the people you serve.','Support access. Build practical capability.','Funders and sponsors can help underwrite technology or participant access.','Evidence before claims.','Tell us what your community needs.','Add optional planning details'];for(const text of requiredOrganizationCopy)if(!organizations.includes(text))failures.push(`Organizations page missing approved partner copy: ${text}`);
const legalPages=['privacy','terms','cookies','acceptable-use','responsible-ai','accessibility','nondiscrimination','data-rights','security','copyright','media-consent','grievances'];for(const slug of legalPages){const file=`site/${slug}/index.html`;if(!exists(file))failures.push(`Missing legal page: ${file}`);else{const source=read(file);if(source.length<2500)failures.push(`Legal page is unexpectedly thin: ${file}`);if(source.includes('AI Capability Lab'))failures.push(`${slug}: old program identity remains`);if(!source.includes('SozoRock AI Lab'))failures.push(`${slug}: AI Lab identity is missing`);if(!source.includes('href="/organizations/"'))failures.push(`${slug}: on-site organization route is missing from generated navigation`);}}
const participantFields=['firstName','lastName','email','region','roleOrOrganization','preferredFormat','technicalExperience','build','sensitiveData','accessNeeds','consent'];for(const field of participantFields)if(!html.includes(`name="${field}"`))failures.push(`Missing participant application field: ${field}`);
const organizationFields=['firstName','lastName','email','roleOrOrganization','region','preferredFormat','organizationType','build','audience','accessNeeds','consent'];for(const field of organizationFields)if(!organizations.includes(`name="${field}"`))failures.push(`Missing organization inquiry field: ${field}`);
if(!html.includes('data-application-type="participant-interest"'))failures.push('Homepage form is missing participant application type.');if(!organizations.includes('data-application-type="organization-interest"'))failures.push('Organization form is missing organization application type.');if(!organizations.includes('<details class="form-more">'))failures.push('Organization form optional planning fields are not progressively disclosed.');if(!js.includes("fetch('/api/applications/start'"))failures.push('Application endpoint is missing from main.js.');if(!js.includes('data-video-dialog')&& !js.includes('[data-video-dialog]'))failures.push('Edward video dialog behavior is missing from main.js.');if(!js.includes('formStartedAt')||!js.includes('applicationType'))failures.push('Form metadata signals are missing.');if(!html.includes('aria-live="polite"')||!organizations.includes('aria-live="polite"'))failures.push('Accessible form status region is missing.');for(const source of [html,organizations])if(!source.includes('Do not submit private customer, patient, student, employee, financial, legal, or account information.'))failures.push('Sensitive-information warning is missing from a primary form.');if(!curriculum.includes('Core learning areas')||!curriculum.includes('For community partners'))failures.push('Curriculum does not match the approved community-training direction.');if(!html.includes('href="/organizations/#inquiry"')||!curriculum.includes('href="/organizations/#inquiry"'))failures.push('Primary organization CTAs do not route to the on-site inquiry flow.');
const htmlFiles=[];(function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else if(entry.name.endsWith('.html'))htmlFiles.push(full);}})(path.join(root,'site'));for(const file of htmlFiles){const source=fs.readFileSync(file,'utf8');const page=path.relative(path.join(root,'site'),file);if(/SozoRock Meridian|Meridian/i.test(source))failures.push(`${page}: Meridian reference remains public`);const hrefs=[...source.matchAll(/href="(\/[^"?#]*)(?:[?#][^"]*)?"/g)].map(m=>m[1]);for(const href of new Set(hrefs)){if(href==='/'||href.startsWith('/api/')||href.startsWith('/assets/'))continue;const rel=href.endsWith('/')?`${href.slice(1)}index.html`:href.slice(1);if(!exists(`site/${rel}`))failures.push(`${page}: broken internal link target ${href}`);}}
if(failures.length){console.error(`Content checks failed (${failures.length}):\n- ${failures.join('\n- ')}`);process.exit(1);}console.log(`Content checks passed: visual-first story, on-site participant media, live project proof, concise pathway, forms, partner flow, ${legalPages.length} policy pages, and no Google Drive links.`);
